# Generated by Django 4.1.2 on 2023-06-07 14:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_alter_event_event_date_alter_event_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='events',
        ),
        migrations.CreateModel(
            name='PointReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 7, 14, 36, 35, 243393, tzinfo=datetime.timezone.utc))),
                ('points_requested', models.DecimalField(decimal_places=1, max_digits=10)),
                ('points_granted', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
