# Generated by Django 4.1.2 on 2023-06-07 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_events_pointreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointreport',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 14, 44, 4, 331931, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Report Date'),
        ),
    ]
