# Generated by Django 4.1.2 on 2023-06-07 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_event_pub_date_alter_pointreport_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 16, 15, 54, 183938, tzinfo=datetime.timezone.utc), verbose_name='Publish Date '),
        ),
        migrations.AlterField(
            model_name='pointreport',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 16, 15, 54, 185598, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Report Date'),
        ),
    ]
