# Generated by Django 4.1.2 on 2023-06-08 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_pointreport_verified_by_alter_event_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 15, 29, 4, 41674, tzinfo=datetime.timezone.utc), verbose_name='Publish Date '),
        ),
        migrations.AlterField(
            model_name='pointreport',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 15, 29, 4, 42592, tzinfo=datetime.timezone.utc), verbose_name='Report Date'),
        ),
    ]
