# Generated by Django 4.1.2 on 2023-06-08 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_event_pub_date_alter_pointreport_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_s_code',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 16, 12, 55, 189190, tzinfo=datetime.timezone.utc), verbose_name='Publish Date '),
        ),
        migrations.AlterField(
            model_name='pointreport',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 16, 12, 55, 190083, tzinfo=datetime.timezone.utc), verbose_name='Report Date'),
        ),
    ]
